#!/usr/bin/env bash

COMMAND="$1"
shift

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: clean-tmp, reset, install, rights, composer-install, composer-update"
    echo "   ldap-reset, ldap-shell, ldap-users"
    echo "   shell, shellroot"
    exit 1;
fi
CONTAINER=jelix_saml_php

case $COMMAND in
    clean-tmp)
        docker exec -t -i $CONTAINER appctl.sh clean_tmp;;
    reset)
        docker exec -t -i $CONTAINER appctl.sh reset;;
    install)
        docker exec -t -i $CONTAINER appctl.sh install;;
    rights)
        docker exec -t -i $CONTAINER appctl.sh rights;;
    composer-install)
        docker exec -t -i $CONTAINER appctl.sh composer_install;;
    composer-update)
        docker exec -t -i $CONTAINER appctl.sh composer_update;;
    #unittests)
    #    docker exec -t -i $CONTAINER appctl.sh unittests;;
    shell)
       docker exec -it --user userphp $CONTAINER  /bin/bash -l;;
    shellroot)
       docker exec -it $CONTAINER  /bin/sh  -l;;
    ldap-reset)
      docker exec -it jelix_saml_ldap /bin/ctl.sh reset
      ;;
    ldap-users)
       docker exec -it jelix_saml_ldap /bin/ctl.sh showusers
       ;;
    ldap-shell)
       docker exec -it jelix_saml_ldap  /bin/bash -l
     ;;
    *)
        echo "wrong command"
        exit 2
        ;;
esac


