#!/usr/bin/env bash

set -e

CMD="$1";
if [ -z "$CMD" ]; then
    CMD="up"
else
    shift
fi

if [ "$CMD" == "reset" ]; then
    # Stop/Remove containers
    docker-compose -p jelix-saml-tests rm -sf || true
    rm -f app/var/config/localconfig.ini.php app/var/config/profiles.ini.php
    rm -f app/var/config/installer.ini.php app/var/config/liveconfig.ini.php
    rm -f app/composer.lock app/var/db/jelix.sqlite
    rm -rf app/temp/app/www
    rm -rf jelix app/vendor
    exit 0
fi

# Create a .env file so that we may use subsequent docker-compose
# commands directly
cat > .env << End-of-env
JELIX_VERSION=${JELIX_VERSION:-1.6.34}
End-of-env


docker-compose -p jelix-saml-tests $CMD "$@"
